---
title: "Involvement and Awards"
---
__All of the following are projects that I have either been involved in as a research intern or as a member of the participating team. Awards I have received are also included.__

* In the summer of 2024, I worked as a research intern at Syracuse University to analyze thawed permafrost samples for dissolved organic carbon, total nitrogen, pH, and other values.
[Dissolved Organic Carbon in Northern Permafrost Information](https://tc.copernicus.org/articles/18/1443/2024/)

* In the opening weekend of the 2024 field hockey season posted back-to-back shutouts to earn MAC Defensive Player of the Week.
[Mid-American Conference Defensive Player of the Week](https://appstatesports.com/news/2024/9/3/field-hockey-bosma-grenis-receive-mac-player-of-the-week-honors)

* Was a member of the 2023 Appalachian State Field Hockey team that won the first championship title in program history.
[2023 MAC Championship Team Roster](https://appstatesports.com/documents/2023/8/10/FH_Roster_Breakdown.pdf)

* Serve as an intern for the Appalachian Geological and Environmental Sciences Department's DAGGER team.
[Devonian Anoxia, Geochemistry, Geochronology, and Extinction Research Team](https://devonian.appstate.edu/personnel)

* Am able to exhibit the skills necessary to combine data sets within RStudio in the STT2860 course at Appalachian State University.
[Combining Data Sets](combining_data_frames.qmd)